# -*- coding: utf-8 -*-
# Generated by Django 1.11.3 on 2017-08-01 11:43
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('questions', '0002_auto_20170801_1126'),
    ]

    operations = [
        migrations.AlterField(
            model_name='posts',
            name='AcceptedAnswerId',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='posts',
            name='ClosedDate',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='posts',
            name='CommunityOwnedDate',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='posts',
            name='DeletionDate',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='tags',
            name='ExcerptPostId',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='questions.Posts'),
        ),
        migrations.AlterField(
            model_name='tags',
            name='WikiPostId',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='votes',
            name='BountyAmount',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
