# -*- coding: utf-8 -*-
# Generated by Django 1.11.3 on 2017-08-01 11:45
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('questions', '0003_auto_20170801_1143'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tags',
            name='Count',
            field=models.IntegerField(default='0'),
        ),
    ]
