# -*- coding: utf-8 -*-
# Generated by Django 1.11.3 on 2017-08-03 08:55
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('questions', '0005_auto_20170801_1347'),
    ]

    operations = [
        migrations.AlterField(
            model_name='posts',
            name='Title',
            field=models.CharField(blank=True, default='Defaultovermine', max_length=140, null=True),
        ),
    ]
